### ISSUE TITLE
Improve error logging for terraform commands

### ISSUE THREAD

**Issue by marcoceppi** [cloud-custodian/pytest-terraform#13]
Currently, failures aren't very clear when they occur and typically dump a traceback like so:

```
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pytest_terraform/tf.py", line 288, in __call__
    return self.create(request, module_dir)
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pytest_terraform/tf.py", line 296, in create
    test_api = self.runner.apply()
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pytest_terraform/tf.py", line 85, in apply
    self._run_cmd(apply_args)
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pytest_terraform/tf.py", line 116, in _run_cmd
    run_cmd(args, cwd=cwd, stderr=subprocess.STDOUT, env=env)
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/bin/terraform', 'apply', '-input=false', '-no-color', '-state=/tmp/pytest-of-root/pytest-0/aws_sqs1/work/../terraform.tfstate', '-auto-approve', '/tmp/pytest-of-root/pytest-0/aws_sqs1/work/tfplan']' returned non-zero exit status 1.
---------------------------- Captured stderr setup -----------------------------
tf create aws_sqs
run cmd ['/bin/terraform', 'init', '-input=false', '-no-color']
run cmd ['/bin/terraform', 'plan', '-input=false', '-no-color', '-state=/tmp/pytest-of-root/pytest-0/aws_sqs1/work/../terraform.tfstate', '-out=/tmp/pytest-of-root/pytest-0/aws_sqs1/work/tfplan']
run cmd ['/bin/terraform', 'apply', '-input=false', '-no-color', '-state=/tmp/pytest-of-root/pytest-0/aws_sqs1/work/../terraform.tfstate', '-auto-approve', '/tmp/pytest-of-root/pytest-0/aws_sqs1/work/tfplan']
```

It'd be better to capture stderr/stdout of each terraform command and wrap subprocess.CalledProcessError in a `pytest_terraform.exceptions.TerraformCommandFailed`

**Comment by kapilt** [comment]
sounds good to me, another thing is perhaps enabling a --tf-debug flag on the cli not sure. there's currently a class variable for it that I set manually.

**Comment by marcoceppi** [comment]
Yeah, I noticed that and was going to expand that as an option. It'll help make the output for errors and the run cmd stuff easier to flag on and off

**Comment by kapilt** [comment]
the switch to always using check_call addressed this issue.
